import 'dotenv/config'

export const LOGIN_ENDPOINT = process.env.VITE_REACT_APP_LOGIN_ENDPOINT
export const REGISTER_ENDPOINT = process.env.VITE_REACT_APP_REGISTER_ENDPOINT
export const QUESTIONS_ENDPOINT = process.env.VITE_REACT_APP_QUESTIONS_ENDPOINT
export const COMMENTS_ENDPOINT = process.env.VITE_REACT_APP_COMMENTS_ENDPOINT
