import { API_URL_BASE } from './apiConnection';
import {
  LOGIN_ENDPOINT,
  COMMENTS_ENDPOINT,
  TOPICS_ENDPOINT,
  CREATE_USER_ENDPOINT
} from './apiEndpoints';

export {
  API_URL_BASE,
  COMMENTS_ENDPOINT,
  LOGIN_ENDPOINT,
  TOPICS_ENDPOINT,
  CREATE_USER_ENDPOINT
};
