export const HOME = '/'
export const TOPIC = '/:authorName/:topicTitle'
export const LOGIN = '/login'
export const REGISTER = '/register'
export const ABOUT_US = '/about-us'
export const USER_PROFILE = '/profile/:userName'
export const CREATE_TOPIC = '/post'
export const ABOUT_PROJECT = '/about-project'
